[project]
name = "ag"
version = "0.1.0"
description = "oba's own agent framework/library aka we have agno at home"
requires-python = ">=3.14"
dependencies = [
    "attrs>=25.4.0",
    "httpx>=0.28.1",
    "pydantic>=2.12.0",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
